### ISSUE TITLE
Mobile/Tablet Visual Issues

### ISSUE THREAD

**Issue by rubidiummoon** [Kedyn/fusliez-notes#39] opened 2020-09-23 05:15 UTC
When you pull the site up in mobile or tablet, the entire display squishes and not all features are usable. The maps don't show up at all for me. If there could be an app or something, that'd be great or just fixing the visuals on mobile/tablet somehow.
![IMG_0026](https://user-images.githubusercontent.com/70395339/93969609-4a9daf80-fd3a-11ea-81d4-5e2f47b4226b.PNG)

**Comment by Kedyn** [comment] 2020-09-23 05:27
Thanks for the report, we are planning on giving support to mobile... as you can see on #15 , which is planned for the next version... once again thank you for taking the time in reporting this issues.

**Comment by Kedyn** [comment] 2020-09-23 05:28
Duplicate of #15

**Closed by Kedyn** 2020-09-23 05:28 UTC
