### ISSUE TITLE
Request: Add desktop version

### ISSUE THREAD

**Issue by jellytoaster** [Kedyn/fusliez-notes#98] opened 2020-10-29 16:32 UTC
I would like a desktop version of this counter because, whenever if you want to drag a player to a list, the among us windows minimizes and its really annoying. If there is a desktop version I will also like a stay on top function.

**Comment by Kedyn** [comment] 2020-10-29 17:38
Duplicate of #28

**Closed by Kedyn** 2020-10-29 17:38 UTC
